### ISSUE TITLE
邻接矩阵

### ISSUE THREAD

**Issue by ivyc1201** [ChyaZhang/ChatTraffic#5]
想问一下代码中的/home/zcy/latent-diffusion-main/datasets/traffic/matrix.npy对应的是Readme数据ChatTraffic/datasets/traffic目录下的matrix.npy吗？

我用了ChatTraffic/datasets/traffic目录下的matrix.npy，以下是报错内容C:\py\anaconda\envs\pytorch\python.exe C:\py\Pycharm2021.2.4\plugins\python\helpers\pydev\pydevconsole.py --mode=client --port=58756
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Users\\123\\Downloads\\ChatTraffic-main', 'C:\\Users\\123\\Downloads\\ChatTraffic-main\\datasets', 'C:/Users/123/Downloads/ChatTraffic-main'])
Python 3.9.20 | packaged by conda-forge | (main, Sep 30 2024, 17:43:23) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.7.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.7.0
Python 3.9.20 | packaged by conda-forge | (main, Sep 30 2024, 17:43:23) [MSC v.1929 64 bit (AMD64)] on win32
runfile('C:/Users/123/Downloads/ChatTraffic-main/main.py', args=['--base', 'configs/latent-diffusion/traffic.yaml', '-t', '--gpus', '1'], wdir='C:/Users/123/Downloads/ChatTraffic-main')
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
Global seed set to 23
Running on GPUs 1
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 400.09 M params.
making attention of type 'vanilla' with 128 in_channels
Working with z of shape (1, 3, 36, 36) = 3888 dimensions.
making attention of type 'vanilla' with 128 in_channels
Traceback (most recent call last):
  File "C:\py\anaconda\envs\pytorch\lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-462cceafee09>", line 1, in <module>
    runfile('C:/Users/123/Downloads/ChatTraffic-main/main.py', args=['--base', 'configs/latent-diffusion/traffic.yaml', '-t', '--gpus', '1'], wdir='C:/Users/123/Downloads/ChatTraffic-main')
  File "C:\py\Pycharm2021.2.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\py\Pycharm2021.2.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/123/Downloads/ChatTraffic-main/main.py", line 587, in <module>
    model = instantiate_from_config(config.model)
  File "C:\Users\123\Downloads\ChatTraffic-main\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\Users\123\Downloads\ChatTraffic-main\ldm\models\diffusion\ddpm.py", line 460, in __init__
    self.instantiate_first_stage(first_stage_config)
  File "C:\Users\123\Downloads\ChatTraffic-main\ldm\models\diffusion\ddpm.py", line 503, in instantiate_first_stage
    model = instantiate_from_config(config)
  File "C:\Users\123\Downloads\ChatTraffic-main\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\Users\123\Downloads\ChatTraffic-main\ldm\models\autoencoder.py", line 309, in __init__
    self.init_from_ckpt(ckpt_path, ignore_keys=ignore_keys)
  File "C:\Users\123\Downloads\ChatTraffic-main\ldm\models\autoencoder.py", line 312, in init_from_ckpt
    sd = torch.load(path, map_location="cpu",weights_only=True)["state_dict"]
  File "C:\py\anaconda\envs\pytorch\lib\site-packages\torch\serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
  File "C:\py\anaconda\envs\pytorch\lib\site-packages\torch\serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\py\anaconda\envs\pytorch\lib\site-packages\torch\serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by ouyangnann** [comment]
datasets/traffic/matrix.npy没有提供。

**Comment by yue0708** [comment]
您好，我看了您的文章很有启发，但遇到了一个问题，我可视化了matrix_roadclass&length.npy邻接矩阵文件，发现提供的数据只有（36,36,2）维，我看了论文中是有1290条路，按照我理解的邻接矩阵定义，应该有1296*1296的维度，0和1表示路段是否相关，但是提供的36*36维的数据有1也有小数，想问问您是否对矩阵做了压缩或其他操作，能否提供一些说明？

**Comment by ChyaZhang** [comment]
> datasets/traffic/matrix.npy没有提供。



> 您好，我看了您的文章很有启发，但遇到了一个问题，我可视化了matrix_roadclass&length.npy邻接矩阵文件，发现提供的数据只有（36,36,2）维，我看了论文中是有1290条路，按照我理解的邻接矩阵定义，应该有1296_1296的维度，0和1表示路段是否相关，但是提供的36_36维的数据有1也有小数，想问问您是否对矩阵做了压缩或其他操作，能否提供一些说明？

邻接矩阵：https://drive.google.com/file/d/1kwkyOLywS63v8-_tZf4eC5NhX22P264Q/view?usp=drive_link
